name: tf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - cudatoolkit=11.2  # Optional: Only include if using CUDA support; can be removed for Binder compatibility
  - cudnn=8.1.0
  - ipykernel
  - jupyterlab
  - matplotlib
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - pillow
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cachetools==5.3.3
      - flatbuffers==24.3.25
      - gast==0.4.0
      - google-auth==2.29.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.62.1
      - h5py==3.10.0
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - markdown==3.6
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==3.19.6
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.1
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - werkzeug==3.0.2
      - wrapt==1.16.0
